### ISSUE TITLE
Option to disable italic

### ISSUE THREAD

**Issue by zerodogg** [hdonnay/solarized#1]
Hi!
Thanks for an excellent port, made the migration to newer nvim quite painless.

Could you add an option to disable italic? In particular comments render terribly with the font I use, and I'm a creature of habit and just plain used to them not being italic.

**Comment by hdonnay** [comment]
I added some knobs to the lua module(s) and then wrote a note about how to use them.

I'd like to avoid the global variable setup that themes usually seem to use as long as possible.
